### ISSUE TITLE
Permissions issue on Android 13

### ISSUE THREAD

**Issue by sowa705** [slavabarkov/tidy#2]
Android 13 removes the READ_EXTERNAL_STORAGE permission that results in zero found images.
This can be fixed by adding:
`<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />`
and an appropriate request:
`permissionsRequest.launch(android.Manifest.permission.READ_MEDIA_IMAGES)`

**Comment by slavabarkov** [comment]
@sowa705 Thank you for the report! Fixed in [1.1](https://github.com/slavabarkov/tidy/commit/e304eff43d4ba250a4b5db06f17665bb73214a42)
